spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: "jdbc:mysql://localhost:3306/amusnet_task_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

